---
# Run linter.
repos:
- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear]

# Local hook to run tests.
- repo: local
  hooks:
  - id: tests
    name: tests
    entry: poetry run pytest
    language: system
    types: [python]
    pass_filenames: false

# Type check code.
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: 'v0.931 '
#   hooks:
#   - id: mypy